
### Extra git aliases from tj holowaychuk ###
alias gca="git commit -a -m"
alias gl="git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"

### my git aliases ###
alias g.s='git browse'
alias gpr='git pull-request -b develop'

### git hubflow ###
alias hpush='git hf push'
alias hupdate='git hf update'
alias hpull='git hf pull'

alias hfs='git hf feature start'
alias hfco='git hf feature checkout'
alias hff='git hf feature finish'

alias hrs='git hf release start'
alias hrf='git hf release finish'

alias hhs='git hf hotfix start'
alias hhf='git hf hotfix finish'


### ohmy functions ###
add_corrects
